/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TreeRelocationRouteImport } from './routes/tree-relocation'
import { Route as TreeProtectionRouteImport } from './routes/tree-protection'
import { Route as TreePlantationRouteImport } from './routes/tree-plantation'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeRelocationRoute = TreeRelocationRouteImport.update({
  id: '/tree-relocation',
  path: '/tree-relocation',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeProtectionRoute = TreeProtectionRouteImport.update({
  id: '/tree-protection',
  path: '/tree-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const TreePlantationRoute = TreePlantationRouteImport.update({
  id: '/tree-plantation',
  path: '/tree-plantation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/tree-plantation': typeof TreePlantationRoute
  '/tree-protection': typeof TreeProtectionRoute
  '/tree-relocation': typeof TreeRelocationRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/tree-plantation': typeof TreePlantationRoute
  '/tree-protection': typeof TreeProtectionRoute
  '/tree-relocation': typeof TreeRelocationRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/mission': typeof MissionRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/tree-plantation': typeof TreePlantationRoute
  '/tree-protection': typeof TreeProtectionRoute
  '/tree-relocation': typeof TreeRelocationRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/gallery'
    | '/impact'
    | '/mission'
    | '/privacy'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/tree-plantation'
    | '/tree-protection'
    | '/tree-relocation'
    | '/volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/gallery'
    | '/impact'
    | '/mission'
    | '/privacy'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/tree-plantation'
    | '/tree-protection'
    | '/tree-relocation'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/contact'
    | '/donate'
    | '/faq'
    | '/gallery'
    | '/impact'
    | '/mission'
    | '/privacy'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/tree-plantation'
    | '/tree-protection'
    | '/tree-relocation'
    | '/volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  ImpactRoute: typeof ImpactRoute
  MissionRoute: typeof MissionRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  TermsRoute: typeof TermsRoute
  TreePlantationRoute: typeof TreePlantationRoute
  TreeProtectionRoute: typeof TreeProtectionRoute
  TreeRelocationRoute: typeof TreeRelocationRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-relocation': {
      id: '/tree-relocation'
      path: '/tree-relocation'
      fullPath: '/tree-relocation'
      preLoaderRoute: typeof TreeRelocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-protection': {
      id: '/tree-protection'
      path: '/tree-protection'
      fullPath: '/tree-protection'
      preLoaderRoute: typeof TreeProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree-plantation': {
      id: '/tree-plantation'
      path: '/tree-plantation'
      fullPath: '/tree-plantation'
      preLoaderRoute: typeof TreePlantationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  ImpactRoute: ImpactRoute,
  MissionRoute: MissionRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  TermsRoute: TermsRoute,
  TreePlantationRoute: TreePlantationRoute,
  TreeProtectionRoute: TreeProtectionRoute,
  TreeRelocationRoute: TreeRelocationRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
